version: '3.8'

services:
  vulnerable-webapp:
    image: vulnerable-webapp:latest
    container_name: vulnerable-webapp-staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - staging-network

networks:
  staging-network:
    driver: bridge 